### ISSUE TITLE
$guestModeEnabled must not be accessed before initialization

### ISSUE THREAD

**Issue by aatvanrees** [Lakshan-Madushanka/laravel-comments#15]
Thanks for this great package! Maybe i'm doing something wrong but when i place a comment and then reply on anotrher comment it works perfect, but when i refresh the page and do a reply without  first making a comment i'm getting: $guestModeEnabled must not be accessed before initialization. I tried including 'protected $guestMode = false; // Auth mode;'  in my 'post' model but that gives me the same error... Any idea? Regards... Aat

**Comment by Lakshan-Madushanka** [comment]
@aatvanrees Sorry for the inconvenience. This is a bug that I had noticed before but forgot to fix. Give me a moment, I'll fix this sooner.

**Comment by aatvanrees** [comment]
Wow, that was extremely fast...  Thanks for the update!
