### ISSUE TITLE
Alpine Expression Error: message is not defined.

### ISSUE THREAD

**Issue by bumpyy** [Lakshan-Madushanka/laravel-comments#44]
### Bug type

- [ ] Style
- [X] Behaviour

### Commenter Version

2.0.3

### Description

i have follow all step but got this error
![image](https://github.com/user-attachments/assets/7db837bb-37b2-4532-9fdf-64b3bd9a87c8)

for context i need to do this in my js file
![image](https://github.com/user-attachments/assets/46b6159c-8b4d-48c6-b098-66db817efe64)

### Steps To Reproduce

see description

**Comment by Lakshan-Madushanka** [comment]
@bumpyy I think you haven't included assets as instructed in https://lakm.gitbook.io/commenter/basics/usage#include-styles-in-your-layout and https://lakm.gitbook.io/commenter/basics/usage#include-scripts-in-your-layout

**Comment by bumpyy** [comment]
already did,
![image](https://github.com/user-attachments/assets/91027cbf-0b97-4bd8-a4fc-48ae82812135)
![image](https://github.com/user-attachments/assets/f21954fb-bbd9-4f93-947c-6a47219ccdd2)

I'm using Laravel 10 btw, gonna try things out to see if it works

**Comment by Lakshan-Madushanka** [comment]
- What is livewire version?. 
- Include `@livewireScripttConfig` before `@commentsStyle`. 
- Also check commenter assets have been published  in `public/vendor/lakm/laravel-comments/build/` directory

If the issue persists, please create a sample Git repository and share the link.

**Comment by bumpyy** [comment]
i'm using livewire 3, i think it's because i'm [manually bundling livewire and alpine](https://livewire.laravel.com/docs/installation#manually-bundling-livewire-and-alpine)

sadly i need to to this to use alpine plugin.

**Comment by bumpyy** [comment]
Sorry for the confusion,
Using the blade directive will not work
![image](https://github.com/user-attachments/assets/b2d4100a-2049-4957-85f0-e3d68ea14ad5)

but we can import it directly in our js and css file
js
![image](https://github.com/user-attachments/assets/02c3a267-6453-4c31-ab4e-d0b59317fb8a)

css
![image](https://github.com/user-attachments/assets/c9ae9ead-83d4-48be-a7f1-f3ada871351e)

this is working but will be a problem (more like a chore) if the file name changed.
perhaps there's a better way?
