### ISSUE TITLE
Model must use the LakM\Comments\Contracts\CommenterContract interface

### ISSUE THREAD

**Issue by dungphanxuanhn** [Lakshan-Madushanka/laravel-comments#45]
### Bug type

Installation

### Commenter Version

Dev

### Description

It not work when install

Class Post Model
`class Post extends Model implements CommenterContract, CommentableContract
{

    use Commentable;
...
`
View

` {{-- Article content --}}
                {!! $modelPost->content!!}

                <x-comments::index :model="$modelPost" />
`

**Comment by dungphanxuanhn** [comment]
![image](https://github.com/user-attachments/assets/42da7866-b51b-44dc-a49e-30121c83635e)

**Comment by Lakshan-Madushanka** [comment]
`CommenterContract` must be implemented by your user model https://lakm.gitbook.io/commenter/basics/usage#implement-commentercontract-and-import-commenter-trait-in-commenter-model
