### ISSUE TITLE
Conflict With My Theme.. Tailwind CSS and Alpine JS

### ISSUE THREAD

**Issue by DavidChriss** [Lakshan-Madushanka/laravel-comments#48]
### Bug type

Style

### Commenter Version

2.0.4

### Description

I have followed all instructions, My current project was having comment system But I replaced it with this.. And when I apply @commentsStyles In my app layout I found that it conflict with my theme that use Tailwind CSS, Alpine JS and Livewire 

It break theme layout and also  the comment section it self not looking good.. (it broken and no comment box)

And in my Console this is what I see

Cookie “XSRF-TOKEN” has been rejected because there is an existing “secure” cookie.

Alpine Expression Error: message is not defined

Expression: "message('595374af-3c36-4678-8f04-0736760b840d')"

 
<div x-cloak="" x-data="message('595374af-3c36-4678-8f04-0736760b840d')" @comment-created.window="show($event.detail.id)">
[app-78822604.js:4:25400](http://flixhq.ink/build/assets/app-78822604.js)
Alpine Expression Error: showMsg is not defined

Expression: "showMsg"

 
<span class="align-top text-xs text-green-500 sm:text-sm" x-show="showMsg" x-transition="">
[app-78822604.js:4:25400](http://flixhq.ink/build/assets/app-78822604.js)
Alpine Expression Error: trailerOpen is not defined

Expression: "trailerOpen"

 
<div class="fixed inset-0 bg-gray-80…z-50 transition-opacity" x-show="trailerOpen" x-transition:enter="transition ease-out duration-200" x-transition:enter-start="opacity-0" x-transition:enter-end="opacity-100" x-transition:leave="transition ease-out duration-100" x-transition:leave-start="opacity-100" x-transition:leave-end="opacity-0" aria-hidden="true" style="display: none;">
[app-78822604.js:4:25400](http://flixhq.ink/build/assets/app-78822604.js)
Alpine Expression Error: trailerOpen is not defined

Expression: "trailerOpen"

 
<div id="search-modal" class="fixed inset-0 z-50 overf…ify-center px-4 sm:px-6" role="dialog" aria-modal="true" x-show="trailerOpen" x-transition:enter="transition ease-in-out duration-200" x-transition:enter-start="opacity-0 trangray-y-4" x-transition:enter-end="opacity-100 trangray-y-0" x-transition:leave="transition ease-in-out duration-200" x-transition:leave-start="opacity-100 trangray-y-0" x-transition:leave-end="opacity-0 trangray-y-4" style="display: none;">
[app-78822604.js:4:25400](http://flixhq.ink/build/assets/app-78822604.js)
Alpine Expression Error: iframeSrc is not defined

Expression: "iframeSrc"

 
<iframe class="w-full aspect-video" :src="iframeSrc" title="Trailer embed" frameborder="0" allow="accelerometer; autoplay;…e-in-picture; web-share" allowfullscreen="">
[app-78822604.js:4:25400](http://flixhq.ink/build/assets/app-78822604.js)
Alpine Expression Error: downloadOpen is not defined

Expression: "downloadOpen"

 
<div class="fixed inset-0 bg-gray-80…z-50 transition-opacity" x-show="downloadOpen" x-transition:enter="transition ease-out duration-200" x-transition:enter-start="opacity-0" x-transition:enter-end="opacity-100" x-transition:leave="transition ease-out duration-100" x-transition:leave-start="opacity-100" x-transition:leave-end="opacity-0" aria-hidden="true" style="display: none;">
[app-78822604.js:4:25400](http://flixhq.ink/build/assets/app-78822604.js)
Alpine Expression Error: downloadOpen is not defined

Expression: "downloadOpen"

 
<div id="download-modal" class="fixed inset-0 z-50 overf…ify-center px-4 sm:px-6" role="dialog" aria-modal="true" x-show="downloadOpen" x-transition:enter="transition ease-in-out duration-200" x-transition:enter-start="opacity-0 trangray-y-4" x-transition:enter-end="opacity-100 trangray-y-0" x-transition:leave="transition ease-in-out duration-200" x-transition:leave-start="opacity-100 trangray-y-0" x-transition:leave-end="opacity-0 trangray-y-4" style="display: none;">
[app-78822604.js:4:25400](http://flixhq.ink/build/assets/app-78822604.js)
Alpine Expression Error: Quill is not defined

Expression: "let editorConfig = JSON.parse('{\u0022debug\u0022:false,\u0022modules\u0022:{\u0022toolbar\u0022:[[{\u0022header\u0022:[1,2,false]}],[\u0022bold\u0022,\u0022italic\u0022,\u0022underline\u0022],[\u0022link\u0022,\u0022code-block\u0022]]},\u0022placeholder\u0022:\u0022Your message here\u0022,\u0022theme\u0022:\u0022snow\u0022}');
        const quill = new Quill(`#${$wire.editorId}`, editorConfig);

        const editorElm = document.querySelector(`#${$wire.editorId} .ql-editor`);
        editorElm.innerHTML = $wire.text;

        const toolbarOptions = editorConfig.modules.toolbar;

        if ( toolbarOptions|| (Array.isArray(toolbarOptions) && toolbarOptions.length > 0)) {
            const toolbarParentElm = document.querySelector(`#${$wire.toolbarId}`);
            const toolbars = Array.from(document.querySelector('.ql-toolbar'));
            toolbarParentElm.append(toolbars.slice(-1));
        }

        if (false) {
            quill.disable();
        }

        const showUserList = () => {
            let userMentioned = false;

            return (content, $wire) => {
                let subContent = content.split(' ').slice(-1);

                if (subContent.toString()[0] === '@') {
                    $wire.dispatch('user-mentioned-' + $wire.editorId, {
                        id: $wire.editorId,
                        content: subContent.toString().slice(1),
                    });
                    userMentioned = true;
                } else if (userMentioned) {
                    $wire.dispatch('user-not-mentioned-' + $wire.editorId);
                    userMentioned = false;
                }
            };
        };

        let showListFunc = showUserList();

        const handleEditorTextChange = (editorElement, $wire) => {
            let html = editorElement.innerHTML;

            if (html === '<p><br></p>' || html === '') {
                $wire.text = '';
                return;
            }
            $wire.text = html;

            debounce(() => showListFunc(editorElement.textContent, $wire))();
        };

        const onMentionedUserSelected = (e, quill, editorElm) => {
            const span = document.createElement('strong');
            const textnode = document.createTextNode(e.detail.name + ' ');
            const lastChild = editorElm.lastChild;
            span.appendChild(textnode);

            lastChild.append(span);

            quill.update();

            quill.setSelection(quill.getLength(), 0);
            quill.format('bold', false);
        };

        quill.on('text-change', () => handleEditorTextChange(editorElm, $wire));

        Livewire.on('user-selected-' + $wire.editorId, () =>
            onMentionedUserSelected(event, quill, editorElm),
        );

        Livewire.on(`reset-editor-${'595374af-3c36-4678-8f04-0736760b840d'}`, (event) => {
            editorElm.innerHTML = event.value;
        });

        Livewire.on(`disable-editor-${'595374af-3c36-4678-8f04-0736760b840d'}`, (event) => {
            quill.disable();
        });"

 
<div wire:snapshot='{"data":{"text":"","id":…e5fc2475c166f77425e52"}' wire:effects="{\"scripts\":{\"13801777…/script>\\n        \"}}" wire:model="$parent.text" x-modelable="$wire.text" wire:id="c0RxQmS8TyNlUvMmfV5C">

And

Uncaught (in promise) ReferenceError: Quill is not defined
    result http://domain.com/build/assets/app-78822604.js line 8 > AsyncFunction:4
    anonymous http://domain.com/build/assets/app-78822604.js line 8 > AsyncFunction:80
    ke http://domain.com/build/assets/app-78822604.js:8
    E http://domain.com/build/assets/app-78822604.js:4
    J http://domain.com/build/assets/app-78822604.js:8
    <anonymous> http://domain.com/build/assets/app-78822604.js:88
    gp http://domain.com/build/assets/app-78822604.js:88
    <anonymous> http://domain.com/build/assets/app-78822604.js:88
    <anonymous> http://domain.com/build/assets/app-78822604.js:88
    _t http://domain.com/build/assets/app-78822604.js:8
    processEffects http://domain.com/build/assets/app-78822604.js:9
    gd http://domain.com/build/assets/app-78822604.js:9
    yd http://domain.com/build/assets/app-78822604.js:9
    sp http://domain.com/build/assets/app-78822604.js:88
    Cn http://domain.com/build/assets/app-78822604.js:8
    I http://domain.com/build/assets/app-78822604.js:4
    I http://domain.com/build/assets/app-78822604.js:4
    ue http://domain.com/build/assets/app-78822604.js:4
    ue http://domain.com/build/assets/app-78822604.js:4
    ue http://domain.com/build/assets/app-78822604.js:4
    ue http://domain.com/build/assets/app-78822604.js:4
    ue http://domain.com/build/assets/app-78822604.js:4
    ue http://domain.com/build/assets/app-78822604.js:4
    ue http://domain.com/build/assets/app-78822604.js:4
    ue http://domain.com/build/assets/app-78822604.js:4
    ue http://domain.com/build/assets/app-78822604.js:4
    ue http://domain.com/build/assets/app-78822604.js:4
    ue http://domain.com/build/assets/app-78822604.js:4
    ue http://domain.com/build/assets/app-78822604.js:4
    ue http://domain.com/build/assets/app-78822604.js:4
    ue http://domain.com/build/assets/app-78822604.js:4
    I http://domain.com/build/assets/app-78822604.js:4
    ei http://domain.com/build/assets/app-78822604.js:8
    I http://domain.com/build/assets/app-78822604.js:4
    me http://domain.com/build/assets/app-78822604.js:4
    me http://domain.com/build/assets/app-78822604.js:4
    sp http://domain.com/build/assets/app-78822604.js:88
    <anonymous> http://domain.com/build/assets/app-78822604.js:103
app-78822604.js line 8 > AsyncFunction:4:23
Uncaught ReferenceError: message is not defined
    anonymous http://domain.com/build/assets/app-78822604.js line 8 > AsyncFunction:3
    ke http://domain.com/build/assets/app-78822604.js:8
    E http://domain.com/build/assets/app-78822604.js:4
    J http://domain.com/build/assets/app-78822604.js:8
    js http://domain.com/build/assets/app-78822604.js:8
    u http://domain.com/build/assets/app-78822604.js:8
    d http://domain.com/build/assets/app-78822604.js:8
    ei http://domain.com/build/assets/app-78822604.js:8
    I http://domain.com/build/assets/app-78822604.js:4
    me http://domain.com/build/assets/app-78822604.js:4
    me http://domain.com/build/assets/app-78822604.js:4
    sp http://domain.com/build/assets/app-78822604.js:88
    <anonymous> http://domain.com/build/assets/app-78822604.js:103
app-78822604.js line 8 > AsyncFunction:3:16
Uncaught ReferenceError: showMsg is not defined
    anonymous http://domain.com/build/assets/app-78822604.js line 8 > AsyncFunction:3
    ke http://domain.com/build/assets/app-78822604.js:8
    E http://domain.com/build/assets/app-78822604.js:4
    js http://domain.com/build/assets/app-78822604.js:8
    H http://domain.com/build/assets/app-78822604.js:4
    z http://domain.com/build/assets/app-78822604.js:4
    X http://domain.com/build/assets/app-78822604.js:4
    ct http://domain.com/build/assets/app-78822604.js:4
    js http://domain.com/build/assets/app-78822604.js:8
    u http://domain.com/build/assets/app-78822604.js:8
    d http://domain.com/build/assets/app-78822604.js:8
    ei http://domain.com/build/assets/app-78822604.js:8
    I http://domain.com/build/assets/app-78822604.js:4
    me http://domain.com/build/assets/app-78822604.js:4
    me http://domain.com/build/assets/app-78822604.js:4
    sp http://domain.com/build/assets/app-78822604.js:88
    <anonymous> http://domain.com/build/assets/app-78822604.js:103
app-78822604.js line 8 > AsyncFunction:3:16
Uncaught ReferenceError: trailerOpen is not defined
    anonymous http://domain.com/build/assets/app-78822604.js line 8 > AsyncFunction:3
    ke http://domain.com/build/assets/app-78822604.js:8
    E http://domain.com/build/assets/app-78822604.js:4
    js http://domain.com/build/assets/app-78822604.js:8
    H http://domain.com/build/assets/app-78822604.js:4
    z http://domain.com/build/assets/app-78822604.js:4
    X http://domain.com/build/assets/app-78822604.js:4
    ct http://domain.com/build/assets/app-78822604.js:4
    js http://domain.com/build/assets/app-78822604.js:8
    u http://domain.com/build/assets/app-78822604.js:8
    d http://domain.com/build/assets/app-78822604.js:8
    ei http://domain.com/build/assets/app-78822604.js:8
    I http://domain.com/build/assets/app-78822604.js:4
    me http://domain.com/build/assets/app-78822604.js:4
    me http://domain.com/build/assets/app-78822604.js:4
    sp http://domain.com/build/assets/app-78822604.js:88
    <anonymous> http://domain.com/build/assets/app-78822604.js:103
2 app-78822604.js line 8 > AsyncFunction:3:16
Uncaught ReferenceError: iframeSrc is not defined
    anonymous http://domain.com/build/assets/app-78822604.js line 8 > AsyncFunction:3
    ke http://domain.com/build/assets/app-78822604.js:8
    E http://domain.com/build/assets/app-78822604.js:4
    Ja http://domain.com/build/assets/app-78822604.js:8
    H http://domain.com/build/assets/app-78822604.js:4
    z http://domain.com/build/assets/app-78822604.js:4
    X http://domain.com/build/assets/app-78822604.js:4
    ct http://domain.com/build/assets/app-78822604.js:4
    Ja http://domain.com/build/assets/app-78822604.js:8
    u http://domain.com/build/assets/app-78822604.js:8
    d http://domain.com/build/assets/app-78822604.js:8
    ei http://domain.com/build/assets/app-78822604.js:8
    I http://domain.com/build/assets/app-78822604.js:4
    me http://domain.com/build/assets/app-78822604.js:4
    me http://domain.com/build/assets/app-78822604.js:4
    sp http://domain.com/build/assets/app-78822604.js:88
    <anonymous> http://domain.com/build/assets/app-78822604.js:103
app-78822604.js line 8 > AsyncFunction:3:16
Uncaught ReferenceError: downloadOpen is not defined
    anonymous http://domain.com/build/assets/app-78822604.js line 8 > AsyncFunction:3
    ke http://domain.com/build/assets/app-78822604.js:8
    E http://domain.com/build/assets/app-78822604.js:4
    js http://domain.com/build/assets/app-78822604.js:8
    H http://domain.com/build/assets/app-78822604.js:4
    z http://domain.com/build/assets/app-78822604.js:4
    X http://domain.com/build/assets/app-78822604.js:4
    ct http://domain.com/build/assets/app-78822604.js:4
    js http://domain.com/build/assets/app-78822604.js:8
    u http://domain.com/build/assets/app-78822604.js:8
    d http://domain.com/build/assets/app-78822604.js:8
    ei http://domain.com/build/assets/app-78822604.js:8
    I http://domain.com/build/assets/app-78822604.js:4
    me http://domain.com/build/assets/app-78822604.js:4
    me http://domain.com/build/assets/app-78822604.js:4
    sp http://domain.com/build/assets/app-78822604.js:88
    <anonymous> http://domain.com/build/assets/app-78822604.js:103
2 app-78822604.js line 8 > AsyncFunction:3:16
Uncaught ReferenceError: Quill is not defined
    result http://domain.com/build/assets/app-78822604.js line 8 > AsyncFunction:4
    anonymous http://domain.com/build/assets/app-78822604.js line 8 > AsyncFunction:80
    ke http://domain.com/build/assets/app-78822604.js:8
    E http://domain.com/build/assets/app-78822604.js:4
    J http://domain.com/build/assets/app-78822604.js:8
    <anonymous> http://domain.com/build/assets/app-78822604.js:88
    gp http://domain.com/build/assets/app-78822604.js:88
    <anonymous> http://domain.com/build/assets/app-78822604.js:88
    <anonymous> http://domain.com/build/assets/app-78822604.js:88
    _t http://domain.com/build/assets/app-78822604.js:8
    processEffects http://domain.com/build/assets/app-78822604.js:9
    gd http://domain.com/build/assets/app-78822604.js:9
    yd http://domain.com/build/assets/app-78822604.js:9
    sp http://domain.com/build/assets/app-78822604.js:88
    Cn http://domain.com/build/assets/app-78822604.js:8
    I http://domain.com/build/assets/app-78822604.js:4
    I http://domain.com/build/assets/app-78822604.js:4
    ue http://domain.com/build/assets/app-78822604.js:4
    ue http://domain.com/build/assets/app-78822604.js:4
    ue http://domain.com/build/assets/app-78822604.js:4
    ue http://domain.com/build/assets/app-78822604.js:4
    ue http://domain.com/build/assets/app-78822604.js:4
    ue http://domain.com/build/assets/app-78822604.js:4
    ue http://domain.com/build/assets/app-78822604.js:4
    ue http://domain.com/build/assets/app-78822604.js:4
    ue http://domain.com/build/assets/app-78822604.js:4
    ue http://domain.com/build/assets/app-78822604.js:4
    ue http://domain.com/build/assets/app-78822604.js:4
    ue http://domain.com/build/assets/app-78822604.js:4
    ue http://domain.com/build/assets/app-78822604.js:4
    ue http://domain.com/build/assets/app-78822604.js:4
    I http://domain.com/build/assets/app-78822604.js:4
    ei http://domain.com/build/assets/app-78822604.js:8
    I http://domain.com/build/assets/app-78822604.js:4
    me http://domain.com/build/assets/app-78822604.js:4
    me http://domain.com/build/assets/app-78822604.js:4
    sp http://domain.com/build/assets/app-78822604.js:88
    <anonymous> http://domain.com/build/assets/app-78822604.js:103

**Comment by Lakshan-Madushanka** [comment]
Forgot to include  @commentsScripts ?

Follow the instructions at https://lakm.gitbook.io/commenter/basics/installation.

**Comment by Lakshan-Madushanka** [comment]
Sorry for the inconvenience CSS conflict issue was something I should have solved before. It just sipped away from my mind. I will solve this tomorrow.

**Comment by Lakshan-Madushanka** [comment]
Fix available in  [2.0.5](https://github.com/Lakshan-Madushanka/laravel-comments/releases/tag/2.0.5). 
Upgrade guide https://github.com/Lakshan-Madushanka/laravel-comments/blob/main/UPGRADE.md#-205

If you manually include livewire frontend assets make sure @commentsScripts is included before @livewireScripts

```html
    <body>
        @commentsScripts
        @livewireScripts
    </body>
</html>
```

Let me know if there are other issues.

**Comment by iRajul** [comment]
Hi @Lakshan-Madushanka I am getting same error with latest release. I am manually bundling Livewire and Alpine. and using `@livewireScriptConfig` instead of `livewireScripts` as stated in documentation https://livewire.laravel.com/docs/installation#manually-bundling-livewire-and-alpine  . How to make it work in that case ?

**Comment by Lakshan-Madushanka** [comment]
@iRajul Documentation was updated https://lakm.gitbook.io/commenter/basics/installation#manually-bundling-livewire-and-alpine.

Let me know the status.

**Comment by iRajul** [comment]
Hi @Lakshan-Madushanka Yes, it working. there is a typo instead of `@commentsScript` it should be `@commentsScripts` . Thanks for this wonderful library.

**Comment by Lakshan-Madushanka** [comment]
You're almost there just see this https://github.com/Lakshan-Madushanka/laravel-comments/issues/48#issuecomment-2495441725
