### ISSUE TITLE
419 Page Expired

### ISSUE THREAD

**Issue by moijafcor** [Lakshan-Madushanka/laravel-comments#50]
### Bug type

Installation, Behaviour

### Commenter Version

2.0

### Description

I hit the 419 Page Expired after importing the view's component on a Jetstream app. 

I followed the installation steps for your package, obviously. I also verified that the routes it calls have the "web" middleware, so the CSRF should be available, cleared cached views, etc.

Have you encountered such an issue before? Any suggestions on where I should start looking into misconfigurations on my system?

Thank you so much for your work!

**Comment by Lakshan-Madushanka** [comment]
I doubt this is related to the package. Try logging out and login again in a new session. Package can work with or without auth (Guest mode). Being livewire component CSRF token must be handled by livewire itself. Might be something wrong with Jetstream ?

Just try [demo app](https://github.com/Lakshan-Madushanka/laravel-comments-demo) to get an overall idea about the commenter

**Comment by moijafcor** [comment]
Thanks for such a fast response! 

Issue solved.

Postmortem:

- The `.env` has` SESSION_DOMAIN=www.example.com`
- The 419 issue happens **only** when the app responds on https://example.com. This is expected because the session's CSRF is only valid for the `www` subdomain (www.example.com). Forcing the reverse proxy to redirect root requests to the www subdomain will prevent the issue from annoying someone.

I did spot something interesting though: if I import `<x-comments::index :model="$post" />` without the enclosing parent `<div></div>` Livewire fires an error (expected for such cases) that you can see on the Browser's Console; is this perhaps because the package's views are not encapsulated?

Thanks again for your kind support!

**Comment by Lakshan-Madushanka** [comment]
Glad to be helpful to you. Second issue is odd as each livewire component is within a parent element. But I'll look into it.
