### ISSUE TITLE
[Bug]: Return value must be of type string, null returned

### ISSUE THREAD

**Issue by Uhasith** [Lakshan-Madushanka/laravel-comments#59]
### Bug type

Installation

### Commenter Version

2.0.9

### Database

mysql

### Description

LakM\Comments\Models\Comment::ownerName(): Return value must be of type string, null returned

I'm using DevDojo Auth package for authentication

![Screenshot 2024-11-25 at 12 34 57](https://github.com/user-attachments/assets/1d34c890-9b1a-44dc-82e1-076e1ee31620)

@

**Comment by Lakshan-Madushanka** [comment]
If you're using a different column for the username, the package assumes it is name by default. Simply specify the correct column name in the `commenter` configuration file.  https://github.com/Lakshan-Madushanka/laravel-comments/blob/cf7445abd2d920ee0976a721f803e65aa88e0578/config/comments.php#L40

**Comment by Uhasith** [comment]
> If you're using a different column for the username, the package assumes it is name by default. Simply specify the correct column name in the `commenter` configuration file.
> 
> https://github.com/Lakshan-Madushanka/laravel-comments/blob/cf7445abd2d920ee0976a721f803e65aa88e0578/config/comments.php#L40

users table has default column => `name`. I'm using Jetstream and Devdojo Auth packages for authentication.

**Comment by Uhasith** [comment]
> > If you're using a different column for the username, the package assumes it is name by default. Simply specify the correct column name in the `commenter` configuration file.
> > https://github.com/Lakshan-Madushanka/laravel-comments/blob/cf7445abd2d920ee0976a721f803e65aa88e0578/config/comments.php#L40
> 
> users table has default column => `name`. I'm using Jetstream and Devdojo Auth packages for authentication.

To Reproduce install a fresh laravel app with jetstream starter kit and set devdojo auth

[Devdojo Auth](https://devdojo.com/auth/docs/install/jetstream)

**Comment by Lakshan-Madushanka** [comment]
Please create a sample repo and share the link. I am prefer if I have write access. Then I can directly work on it with exact your dependencies.

**Comment by Lakshan-Madushanka** [comment]
Make sure users table doesn't have name column with a null value

**Comment by Lakshan-Madushanka** [comment]
Make sure users's table doesn't have a null value for the name column.
