### ISSUE TITLE
[UI Suggestion]: Comment Section UI Suggestion / New Theme

### ISSUE THREAD

**Issue by DavidChriss** [Lakshan-Madushanka/laravel-comments#61]
### Bug type

Style

### Commenter Version

2.0.9

### Mode

Auth

### Database

mysql

### Description

Hi, I have New Suggestion for the theme as the current themes are not looking modern.. So I have suggestion for the ready made UI but it will need integration with your system.. 

here is The link of that modern Comment UI: https://github.com/ashrafalmayah/ashrafalmayah.github.io/tree/main/interactive-comments-section-main

Thanks hope you will add new themes at some point..

**Comment by Lakshan-Madushanka** [comment]
> Here is the Preview..
> 
> https://interactive-comments-section-nine.vercel.app/
> 
> You may not support nested reply.. since you have good reasons with that
> 
> But here is the suggestion.. users can click reply on sub comments instead of displaying as nested replies it should tag specific user with @UsernameExample where by when user click on that username tagged in reply it should scroll and highlight specific tagged user comment..
> 
> Thanks much.. for the work in this..

This should be posted [here](https://github.com/Lakshan-Madushanka/laravel-comments/discussions/categories/ideas) with a more detailed explanation.

**Comment by Lakshan-Madushanka** [comment]
Haven't released yet as documentation is still in progress but you can test this by setting `"minimum-stability": "stable"` and `"lakm/laravel-comments": "dev-main"` in `composer.json`

**Comment by Lakshan-Madushanka** [comment]
See [v2.1.0](https://github.com/Lakshan-Madushanka/laravel-comments/releases/tag/2.1.0)
