### ISSUE TITLE
Event CommentCreated

### ISSUE THREAD

**Issue by janczakb** [Lakshan-Madushanka/laravel-comments#68]
Hi,

Could you show me an example of how to trigger a new comment creation event with respect to `LakM\Comments\Events\CommentCreated`
?

**Comment by Lakshan-Madushanka** [comment]
Not clear what you exactly meant. Those events are trigger by the package. You can just consume them as you do  laravel event and listners.

**Comment by janczakb** [comment]
I'm trying to call this function using event and listners but it doesn't work for me, could you prepare some short demo video showing how to call this trigger correctly? I would appreciate your help

**Comment by Lakshan-Madushanka** [comment]
Please provide related code sample.

**Comment by janczakb** [comment]
File AppServiceProvider.php

```
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\Event;
use LakM\Comments\Events\CommentCreated;
use App\Listeners\SendCommentConfirmation;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        Event::listen(
            CommentCreated::class,
            SendCommentConfirmation::class,
        );
    }
}
```

File : Listeners/SendCommentConfirmation.php
```

<?php

namespace App\Listeners;

use App\Events\CommentCreate;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Queue\InteractsWithQueue;

class SendCommentConfirmation
{
    /**
     * Create the event listener.
     */
    public function __construct()
    {
        //
    }

    /**
     * Handle the event.
     */
    public function handle(CommentCreate $event): void
    {
        print_r('<br>'.$event->email. ' save it as a order email');
    }
}
```

**Comment by Lakshan-Madushanka** [comment]
I'll look into this.

**Comment by Lakshan-Madushanka** [comment]
But at a glance inside handle method of your listner you must expect LakM\Comments\Events\CommentCreated event as the argument.

**Comment by janczakb** [comment]
I applied your advice and now it works fine.
`public function handle(CommentCreated $event): void`
another question how can I get the comment id? $event->id does not return this data to me

**Comment by Lakshan-Madushanka** [comment]
$event->model->id
