### ISSUE TITLE
How to integrate with Filamentphp?

### ISSUE THREAD

**Issue by Mohammed-800** [Lakshan-Madushanka/laravel-comments#9]

**Comment by Lakshan-Madushanka** [comment]
@Mohammed-800  Thanks for the very first issue. Could you please clarify what you mean? I'm not sure I understand.

**Comment by Mohammed-800** [comment]
@Lakshan-Madushanka  Do you know about Filamentphp ?
https://filamentphp.com

**Comment by Mohammed-800** [comment]
@Lakshan-Madushanka  how to add action for add new comment  List of post 
?

**Comment by Lakshan-Madushanka** [comment]
@Mohammed-800 I know Filamentphp. In fact [admin-panel ](https://github.com/Lakshan-Madushanka/laravel-comments-admin-panel)of the commenter uses filament. But I really don't understand what you mean.

**Comment by Mohammed-800** [comment]
@Lakshan-Madushanka  I want to add  action button every column 
![image](https://github.com/user-attachments/assets/916af2dc-1002-428e-ad41-3f21b2149927)

**Comment by Lakshan-Madushanka** [comment]
@Mohammed-800 Perhaps you mean something [like this](https://github.com/Lakshan-Madushanka/laravel-comments-admin-panel/blob/main/src/Livewire/Admin/CommentForm.php)

**Comment by Mohammed-800** [comment]
@Lakshan-Madushanka 


when click button comment open slide for add comment 
see to photoses
![image](https://github.com/user-attachments/assets/30ad5c85-36b7-4f65-a2a2-d7dc1f57e4b3)
after click I wann like this 
![image](https://github.com/user-attachments/assets/65cd8cdc-f6c2-44bf-98ac-f136652f7e7b)

**Comment by Lakshan-Madushanka** [comment]
@Mohammed-800 I got it. This has already implemented in [admin-panel](https://github.com/Lakshan-Madushanka/laravel-comments-admin-panel)

You can use it to manage comments.

**Comment by Mohammed-800** [comment]
@Lakshan-Madushanka  I want to use the comments inside admin panel for any Resource

**Comment by Mohammed-800** [comment]
@Lakshan-Madushanka  At the same time, I want to activate comments within the admin panel, not controlling them.

**Comment by Lakshan-Madushanka** [comment]
> @Lakshan-Madushanka I want to use the comments inside admin panel for any Resource

Admin-panel package filter for all the resources that has used commenter. Please try it and see.

**Comment by Lakshan-Madushanka** [comment]
> @Lakshan-Madushanka At the same time, I want to activate comments within the admin panel, not controlling them.

Did you mean approve comments. If so admin-panel has exact functionality.

**Comment by Mohammed-800** [comment]
@Lakshan-Madushanka I have bug when     composer require lakm/laravel-comments-admin-panel -W
![image](https://github.com/user-attachments/assets/0165b013-904f-4ff2-a7d6-a95630669844)

**Comment by Lakshan-Madushanka** [comment]
@Mohammed-800 Fix it with [this.](https://github.com/Lakshan-Madushanka/laravel-comments-admin-panel) Please tell me if it works now. Thanks for pointing this.

**Comment by Mohammed-800** [comment]
@Lakshan-Madushanka  still that bug
![image](https://github.com/user-attachments/assets/13ebc331-aee3-4c74-8042-6972b2fd38aa)

**Comment by Mohammed-800** [comment]
@Lakshan-Madushanka  see to photos maybe you can understand me what I mean 
 
![image](https://github.com/user-attachments/assets/6259c947-b9d9-4f8b-8692-fee0bc04dffa)
![image](https://github.com/user-attachments/assets/27f1467c-fe24-4ee2-abdb-7618115fc9e2)
![image](https://github.com/user-attachments/assets/fe23debb-c117-4465-93c8-9707a156b594)
![image](https://github.com/user-attachments/assets/8e93088f-26d0-4051-ade6-8a7442ac52da)

**Comment by Lakshan-Madushanka** [comment]
@Mohammed-800 Admin panel should work as expected. It was my mistake that I didn't release new version.

It seems like you want to use this inside your own admin panel. You can do that but you haven't setup the package properly. Error in the last image has occurs as you haven't implemented relevant interfaces in your models please consult documentation's  [installation](https://lakm.gitbook.io/commenter/basics/installation) and [usage](https://lakm.gitbook.io/commenter/basics/usage) sections. You can also see demo videos.

**Comment by Mohammed-800** [comment]
@Lakshan-Madushanka  still error last my image 
![image](https://github.com/user-attachments/assets/67ffc323-dcd8-4f8e-b1f1-4076e4a2ed36)

**Comment by Lakshan-Madushanka** [comment]
@Mohammed-800 What is the error ?  have you implemented CommnterContract in your user model

**Comment by Mohammed-800** [comment]
@Lakshan-Madushanka  do you mean like thisn ?

![image](https://github.com/user-attachments/assets/9ff0e3cc-31a1-467e-8613-a1a96ca8a869)

**Comment by Lakshan-Madushanka** [comment]
@Mohammed-800 You should also implement the CommenterContract

**Comment by Mohammed-800** [comment]
@Lakshan-Madushanka  like this ?
![image](https://github.com/user-attachments/assets/1afb0b2f-c371-4060-b780-3b7e98e9a44a)
after implement see why is it like this?

![image](https://github.com/user-attachments/assets/d8c2a795-47b6-4288-8514-a90750da642c)

**Comment by Lakshan-Madushanka** [comment]
@Mohammed-800 Because you haven't included styles. Could you please go through the documentation.

> @Mohammed-800 Admin panel should work as expected. It was my mistake that I didn't release new version.
> 
> It seems like you want to use this inside your own admin panel. You can do that but you haven't setup the package properly. Error in the last image has occurs as you haven't implemented relevant interfaces in your models please consult documentation's [installation](https://lakm.gitbook.io/commenter/basics/installation) and [usage](https://lakm.gitbook.io/commenter/basics/usage) sections. You can also see demo videos.

**Comment by Mohammed-800** [comment]
@Lakshan-Madushanka  ok but brother
I don't have layout where I can include styles? PLASE

**Comment by Lakshan-Madushanka** [comment]
@Mohammed-800 wherever your html those assets are simply wrappers around packages's css and js so put them as you normally does.

**Comment by Mohammed-800** [comment]
@Lakshan-Madushanka  not work 
![image](https://github.com/user-attachments/assets/da38a064-dba5-4297-947f-111253dc1c9e)

**Comment by Mohammed-800** [comment]
@Lakshan-Madushanka  see this image

![image](https://github.com/user-attachments/assets/2ddc0ebb-c397-4657-90e8-6139c55ad070)

**Comment by Lakshan-Madushanka** [comment]
@Mohammed-800 Clearly assets haven't added correctly try installing npm dependencies and running dev server

If it is still getting errors. I recommend you to setup the [demo](https://github.com/Lakshan-Madushanka/laravel-comments-demo) project which works fine if you follow the instructions to get insight about the project. Study it you will be able to debug yourself.

**Comment by Mohammed-800** [comment]
@Lakshan-Madushanka 
My brother, I want your help. Please help me. I am confused. I could not activate the comment feature in this way. I have the button to create a new comment that should be activated automatically. I want to do an example, you and I. I will be very grateful to you.

![image](https://github.com/user-attachments/assets/4f499aa7-7397-41bc-b413-47d95b8d3668)

**Comment by Mohammed-800** [comment]
@Lakshan-Madushanka  when click button blue create not show text box,
And I want enable as Authmode alows
